image: alpine

create docs page:
  stage: deploy
  script:
    - apk --no-cache add py2-pip python-dev
    - apk --no-cache add make
    - pip install -r requirements.txt
    - pip install -e .
    - make html -C docs
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - tags

publish to pypi:
  stage: deploy
  script:
    - apk --no-cache add py2-pip python-dev
    - pip install twine
    - python setup.py sdist
    - printenv
    - twine upload dist/*